// italentwebsite/src/components/internationalisering/internationalisering.jsx
import React  from 'react';
import BusIt from './busit';
import Stage from './stage';

const Internationalisering = () => {
    return (
        <div id="tabs">
            <div className="container">
                <h6 className="section-title h1">Internationalisering</h6>
                <div className="row">
                    <div className="col-xs-12 ">
                        <nav>
                            <div className="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                                <a className="nav-item nav-link active" id="nav-stage-tab" data-toggle="tab" href="#nav-stage" role="tab" aria-controls="nav-stage" aria-selected="true">Internationale Stage</a>
                                <a className="nav-item nav-link" id="nav-busit-tab" data-toggle="tab" href="#nav-busit" role="tab" aria-controls="nav-busit" aria-selected="false">BusIT 2017</a>
                            </div>
                        </nav>
                        <div className="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
                            <div className="tab-pane fade " id="nav-busit" role="tabpanel" aria-labelledby="nav-busit-tab">
                                <BusIt />
                            </div>
                            <div className="tab-pane fade show active" id="nav-stage" role="tabpanel" aria-labelledby="nav-stage-tab">
                                <Stage />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br></br>
            <br></br>
            <br></br>
        </div>
    );
};

export default Internationalisering;

// italentangular/src/app/components/internationalisering/internationalisering.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-internationalisering',
  templateUrl: './internationalisering.component.html',
  styleUrls: ['./internationalisering.component.css']
})
export class InternationaliseringComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div id="tabs">
  <div class="container">
      <div class="row">
          <div class="col-xs-12 ">
              <nav>
                  <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                      <a class="nav-item nav-link active" id="nav-busit-tab" data-toggle="tab" href="#nav-busit" role="tab" aria-controls="nav-busit" aria-selected="true">BusIT 2017</a>
                      <a class="nav-item nav-link " id="nav-stage-tab" data-toggle="tab" href="#nav-stage" role="tab" aria-controls="nav-stage" aria-selected="false">Internationale Stage</a>
                    </div>
              </nav>
              <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
                  <div class="tab-pane fade show active" id="nav-busit" role="tabpanel" aria-labelledby="nav-busit-tab">
                      <app-bus-it></app-bus-it>
                  </div>
                  <div class="tab-pane fade " id="nav-stage" role="tabpanel" aria-labelledby="nav-stage-tab">
                      <app-stage></app-stage>
                  </div>
              </div>
          </div>
      </div>
      <br>
      <div class="row">
          <app-internationaliseringref></app-internationaliseringref>
      </div>
  </div>
</div>
