// italentwebsite/src/components/internationalisering/busit.jsx
import React  from 'react';

const BusIt = () => {
    return (
        <div className="container">
            <h3>BusIT 2017 - “Location Based Mobile Apps for Android”</h3>
            <h4>02/04/2017 - 07/04/2017 @ Mendel University, Brno, Tsjechië</h4>
            <br></br>

            <p>Al enkele jaren organiseren enkele school verspreid over de wereld een project genaamd BusIT, hierbij worden studenten van verschillende scholen voor een korte periode uitgewisseld om op een andere school iets bij te leren, over een IT-gerelateerd onderwerp en ook om kennis te maken met de cultuur van een ander land.</p>
            <p>Ik heb in 2017 meegedaan aan de BusIT week die georganiseerd werd door de Mendel University in Brno, Tsjechië. Deze week vond plaats tussen zondag 2 april 2017 en vrijdag 7 april 2017 en had als thema “Location Based Mobile Apps for Android”.</p>
            <p>Als iemand die op dat punt een grote fan was van Android, maar er zelf nog nooit mee gespeelt had en bovendien altijd wel eens naar Tsjechië had willen reizen, klonk dit als een match made in heaven. Iedere dag van dit avontuur zal afzonderlijk besproken worden. </p>
            <br></br>

            <h5>Verslag</h5>
            <h5>Zondag, 02/04/2017</h5>
            <p> Ik kwam aan op zondag 2 april. Deze dag bestond enkel uit een klein welkomstfeestje waar iedereen elkaar kon leren kennen. Tijdens dit feestje moest iedereen zichzelf voorstellen en een snack meenemen wat typisch was voor het land waar je vandaan komt, het spreekt voor zich dat ik gekozen heb voor chocolade.</p>
            <p>Een klein minpuntje, bijna iedereen aanwezig kwam uit België. Er waren maar drie uitzonderingen, waarvan twee uit Tsjechië en één iemand uit Nederland. Jammer genoeg heeft dit ervoor gezorgd dat vrijwel alle communicatie tussen de deelnemers verliep in het Nederlands en niet in het Engels zoals de bedoeling was. Wat de internationale ervaring toch een wel een beetje minder “internationaal” deed aanvoelen.</p>
            <p>Deze bijeenkomst vond plaats in de inkomhal van het internaat waar we verbleven en startte om 18.00 uur ‘s avonds. Vele zijn echter blijven plakken tot in de late uurtjes.</p>
            <br></br>

            <h5>Maandag, 03/04/2017</h5>
            <p>Maandag morgen om 08.00 ’s morgens starten de eerste echte dag van de Bus-IT week. We werden in teams verdeeld en moesten via een app een kennismakingsspel spelen wat ons uiteindelijk tot de campus leiden waar we de volgende dagen zouden vertoeven. Deze app was een bare-bones model waar alles inzit wat we de komende dagen zouden leren.</p>
            <p>Rond 09.00 waren alle groepen aangekomen op de campus en werden we voorgesteld aan de verschillende lectoren, namelijk Jaromir Landa en Jan Kolomaznik. Tot op dit moment hadden we enkel kennis gemaakt met Pavel Turčínek die de hele week in goede banen zou leiden.</p>
            <p>Tot 10.00 uur kregen we van Jaromir korte inleiding van het Android platform. Deze uitleg ging er (gelukkig) vanuit dat je geen voorkennis had van het Android platform, maar verwachten wel dat je kennis had van Java en de Object Oriented (OO) principes begreep.</p>
            <p>Dit ging heel snel, er moest heel erg veel gezien worden. Hierdoor was er jammer genoeg niet zo heel veel tijd om vragen te stellen over wat we nu precies allemaal aan het doen waren. </p>
            <p>Om 10.00 nam Jan de presentatie over en begonnen we effectief met praktische kennis op te doen. Tot 12.00 uur werd er verteld over de basiselementen zoals activities, layouts en lifecycle events. </p>
            <p>In tegenstelling tot Jaromir had Jan een accent wat heel wat minder verstaanbaar was, dit hadden Jan en Jaromir zelf ook door. Alle toekomstige lessen werden daardoor full-time overgenomen door Jaromir.</p>
            <p>Na de middag pauze mochten we toen uiteindelijk zelf beginnen met programmeren. De kennis die we deze voormiddag opgedaan hadden werd ons stap voor stap uitgelegd terwijl we deze moesten toepassen in een test project. </p>
            <p>Dit testproject zou later gaan uitgroeien tot de applicatie die we deze week moesten ontwikkelen. </p>
            <p>Om 17.00 uur werd de eerste lesdag stopgezet. Pavel had een evenement gepland in de stad zelf, dit bleek een heuse party-tram te zijn achteraf. Waarin gratis drank en eten beschikbaar was terwijl we verschillende stukken van de stad te zien kregen.</p>
            <br></br>

            <h5>Dinsdag, 04/04/2017</h5>
            <p>De tweede dag begon met een seminarie over het gebruik van de Maps API van Google en het gebruik van de Estimote Beacons. Dit nam heel veel tijd in beslag en heeft ervoor gezorgd dat we niet veel meer theorie gezien hebben die dag.</p>
            <p>Natuurlijk, het onderwerp van deze week was “Location-Based apps” dus het was te verwachten dat dit enige tijd in beslag ging nemen. Het was bovendien een uitgebreid onderwerp waar heel veel over te vertellen was en heel veel in mogelijk was.</p>
            <br></br>

            <h5>Woensdag, 05/04/2017</h5>
            <p>Woensdagvoormiddag werden alle seminaries afgewerkt die we nodig hadden om zelf te kunnen beginnen ontwikkelen. Hier werd vooral aandacht besteed aan de verschillende “activity triggers” die we moesten gebruiken de komende dagen.</p>
            <p>In de namiddag was het tijd om te brainstormen en ons idee uit te leggen bij Jaromir en Jan. Zij zouden dan kijken of het de moeite was en of het haalbaar was om dit te maken op de resterende tijd.</p>
            <p>Het team waar ik in zat had besloten om een mobiele variant van Cluedo te ontwikkelen. De map die je meekrijgt zou je leiden naar verschillende vraagstukken en ieder vraagstuk dat je juist beantwoorden zou een hint opleveren over wie de dader was.</p>
            <p>Nadat je op het einde van het spel kwam kreeg je een lijst te zien met alle mogelijke daders en moest je de correcte uit het lijstje kiezen. Iedere vraag die juist beantwoord werd (inclusief het kiezen van de dader) leverde punten op.</p>
            <p>Nadat ons idee was goedgekeurd werd er hier de rest van de dag aan verder gewerkt. In tegenstelling tot andere groepen hadden wij besloten geen mock-ups te maken, ons design zouden we simpel houden en wij zouden vooral focussen op een applicatie die werkte en alle nodige functionaliteit bevatten.  Wij begonnen daarom al onmiddellijk met programmeren in tegenstelling tot alle andere groepen.</p>
            <br></br>

            <h5>Donderdag, 06/04/2017</h5>
            <p>De voorlaatste dag was volledig gewijd aan het werken aan de app. Van ’s morgens 08.30 tot 18.00 ben ik bezig geweest, met enkel in korte pauze tijdens de middag.</p>
            <p>Hier liep het jammer genoeg een beetje mis, aangezien niet iedereen van mijn team even gemotiveerd was om samen te werken. Enkele teamleden kwamen zelfs meerdere uren te laat opdagen, of vertrokken vele uren te vroeg en deden niets tot weinig gedurende de dag.</p>
            <p>Dit was jammer, aangezien het werk hierdoor grotendeels op mijn en twee andere teamleden gevallen was. Dit zou ons echter niet tegenhouden, wij zouden er het beste van maken. Iets wat niet altijd even makkelijk was want dit was toch wel een uitdagend project.</p>
            <p>We hadden redelijk wat boilerplate code die we moesten aanpassen, maar dit leiden vaak tot problemen en crashes. Gelukkig waren Jan en Jaromir meer dan bereid om te komen helpen in deze situaties.</p>
            <p>Nadat de werkdag was afgelopen was er nog een wijndegustatie georganiseerd die diende als afscheidsfeestje. Ik ben altijd wel te vinden voor een glaasje alcohol, zeker voor meerdere, dus ik heb veel plezier beleefd aan deze avond.</p>
            <p>Gedurende deze avonden werden er meerdere roden en witte wijnen voorgeschoteld, deze varieerde radicaal van kwaliteit. Er waren er bij die ik enorm goed vond, maar het tegenovergestelde was ook waar. Bij sommige glazen heb ik echt moeite moeten doen om het leeg te kunnen drinken. </p>
            <p>De wijn was vergezeld van zelfgemaakt brood en kaas. Ja hoor, meer dan een geslaagde avond. </p>
            <br></br>

            <h5>Vrijdag, 07/04/2017</h5>
            <p>De laatste dag hadden we nog een uurtje de tijd gekregen om onze app af te maken. Gedurende deze periode was het enige wat in mijn groep nog moest gebeuren het kiezen van de locatie van de vraagstukken. </p>
            <p>Normaal zou na dit uurtje, iedere groep iedere app moeten gaan testen en beoordelen. Maar zo ver is het jammer genoeg nooit gekomen vanwege het slechte weer. Wat ik zeer jammer vond, enkel de groep waarin ik zat heeft uiteindelijk een volledig werkende app afgeleverd en het eindresultaat mocht zeker gezien worden.</p>
            <p>De noodoplossing was een PowerPointpresentatie  maken van je app, en deze dan te pitchen naar de andere groepen. Op basis van deze presentatie werd vervolgens een score toegekend. Persoonlijk vond ik dit heel oneerlijk (aangezien de winnende groep niet meer dan wireframes had en nog geen lijn cde had geschreven).</p>
            <p>De winnaar kreeg een set mee van drie Estimote Beacons. Omdat er nog één pak over was hebben Jaromir en Jan deze nog uitgedeeld aan de mensen waarin zij potentieel zagen en die goed meegewerkt hadden deze week. Twee van deze drie overblijvende beacons zijn uiteindelijk in handen gevallen van een PXL student, waaronder eentje in die van mij.</p>
            <p>Hierna was er nog een korte speech van Pavel, Jaromir en Jan en zat het officiële programma van de Bus-IT week er volledig op.</p>
            <br></br>

            <h5>Reflectie</h5>
            <p>De BusIT week was een uiterst leerrijke week voor mij. Terwijl ik wel al kennis had van Java, de taal die gebruikt wordt bij Android development voelde alles hier toch volledig nieuw aan. De manier waarop je moet programmeren in Android is totaal anders dan de manier waarop ik tot nu toe gewoon Java gedaan heb.</p>
            <p>Android zit fundamenteel anders in elkaar dan Java, zo denk ik al snel aan activities en lifecycle events die de hele flow van je applicatie bepalen. De GUI die op een totaal andere manier ontwikkeld wordt en alles wat met resources te maken heeft. Hoe je een lijst kan maken waar je door scrolt was ook iets wat veel uitgebreider was dan dat ik verwacht had. Allemaal belangrijke elementen van Android, en mobile development in het algemeen, die niet te vinden zijn in Java zelf.</p>
            <p>Dit is dan ook nog niet eens het enige nieuwe wat ik hier geleerd heb. We hebben hier niet enkel de basis gezien van Android development maar ook nog enkele geavanceerde technieken. Het gebruik van Google Maps of de Estimote Beacons zijn hier voorbeelden van.</p>
            <p>Ik ben blij dat ik een goede beheersing had van Java toen ik deze week aanvatten. Ik vrees dat het heel wat minder vlot verlopen zou zijn, moest dit niet het geval geweest zijn. Er was al maar heel weinig tijd om dit project af te kunnen ronden, mocht ik in een taal hebben moeten werken die ik minder goed beheerste denk ik niet dat ik alles werkende gekregen zou hebben. </p>
            <p>Ik ben zeer blij hier aan meegedaan te hebben, want alles wat ik hier geleerd heb wordt natuurlijk ook meegenomen in mijn verdere carrière, zowel op school als in mijn latere loopbaan. Deze week heeft mij ook een enorme boost gegeven voor het vak Mobile Development wat ik in het laatste jaar van mijn opleiding gevolgd heb, aangezien vrijwel alles wat er tijdens deze lessen behandeld geworden geweest is, als kort aan bod gekomen is tijdens de BusIT week.</p>
            <p>Ik zou deze ervaring zo opnieuw doen mocht ik de kans krijgen, want het is uiteindelijk niet allemaal “work” er is ook genoeg tijd beschikbaar voor “pleasure”. Tijdens deze week heb ik ook kunnen genieten van een ander land en heb ik ook daar veel gezien en bij geleerd. Ik heb niet alleen nieuwe technologieën leren kennen, maar je leert ook andere mensen kennen van over de hele wereld en ermee samenwerken. Ik heb de BusIT opgenomen in mijn portfolio omdat ik dit een ongelofelijk ervaring vond, een ervaring die gedeeld moest worden en één van de hoogtepunten van mijn opleiding.</p>     
        </div>
    );
};

export default BusIt;

// italentangular/src/app/components/bus-it/bus-it.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-bus-it',
  templateUrl: './bus-it.component.html',
  styleUrls: ['./bus-it.component.css']
})
export class BusItComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
  <h3>BusIT 2017 - “Location Based Mobile Apps for Android”</h3>
  <h4>02/04/2017 - 07/04/2017 @ Mendel University, Brno, Tsjechië</h4>
  <br>

  <p>Al enkele jaren organiseren enkele school verspreid over de wereld een project genaamd BusIT, hierbij worden studenten van verschillende scholen voor een korte periode uitgewisseld om op een andere school iets bij te leren, over een IT-gerelateerd onderwerp en ook om kennis te maken met de cultuur van een ander land.</p>
  <p>Ik heb in 2017 meegedaan aan de BusIT week die georganiseerd werd door de Mendel University in Brno, Tsjechië. Deze week vond plaats tussen zondag 2 april 2017 en vrijdag 7 april 2017 en had als thema “Location Based Mobile Apps for Android”.</p>
  <p>Als iemand die op dat punt een grote fan was van Android, maar er zelf nog nooit mee gespeelt had en bovendien altijd wel eens naar Tsjechië had willen reizen, klonk dit als een match made in heaven. Iedere dag van dit avontuur zal afzonderlijk besproken worden. </p>
  <br>

  <h5>Verslag</h5>
  <h5>Zondag, 02/04/2017</h5>
  <p> Ik kwam aan op zondag 2 april. Deze dag bestond enkel uit een klein welkomstfeestje waar iedereen elkaar kon leren kennen. Tijdens dit feestje moest iedereen zichzelf voorstellen en een snack meenemen wat typisch was voor het land waar je vandaan komt, het spreekt voor zich dat ik gekozen heb voor chocolade.</p>
  <p>Een klein minpuntje, bijna iedereen aanwezig kwam uit België. Er waren maar drie uitzonderingen, waarvan twee uit Tsjechië en één iemand uit Nederland. Jammer genoeg heeft dit ervoor gezorgd dat vrijwel alle communicatie tussen de deelnemers verliep in het Nederlands en niet in het Engels zoals de bedoeling was. Wat de internationale ervaring toch een wel een beetje minder “internationaal” deed aanvoelen.</p>
  <p>Deze bijeenkomst vond plaats in de inkomhal van het internaat waar we verbleven en startte om 18.00 uur ‘s avonds. Vele zijn echter blijven plakken tot in de late uurtjes.</p>
  <br>

  <h5>Maandag, 03/04/2017</h5>
  <p>Maandag morgen om 08.00 ’s morgens starten de eerste echte dag van de Bus-IT week. We werden in teams verdeeld en moesten via een app een kennismakingsspel spelen wat ons uiteindelijk tot de campus leiden waar we de volgende dagen zouden vertoeven. Deze app was een bare-bones model waar alles inzit wat we de komende dagen zouden leren.</p>
  <img src="../../../assets/images/busit/busit1.jpg" alt="Group going to campus"  class="img-fluid" />
  <br>
  <br>
  <p>Rond 09.00 waren alle groepen aangekomen op de campus en werden we voorgesteld aan de verschillende lectoren, namelijk Jaromir Landa en Jan Kolomaznik. Tot op dit moment hadden we enkel kennis gemaakt met Pavel Turčínek die de hele week in goede banen zou leiden.</p>
  <p>Tot 10.00 uur kregen we van Jaromir korte inleiding van het Android platform. Deze uitleg ging er (gelukkig) vanuit dat je geen voorkennis had van het Android platform, maar verwachten wel dat je kennis had van Java en de Object Oriented (OO) principes begreep.</p>
  <p>Dit ging heel snel, er moest heel erg veel gezien worden. Hierdoor was er jammer genoeg niet zo heel veel tijd om vragen te stellen over wat we nu precies allemaal aan het doen waren. </p>
  <p>Om 10.00 nam Jan de presentatie over en begonnen we effectief met praktische kennis op te doen. Tot 12.00 uur werd er verteld over de basiselementen zoals activities, layouts en lifecycle events. </p>
  <p>In tegenstelling tot Jaromir had Jan een accent wat heel wat minder verstaanbaar was, dit hadden Jan en Jaromir zelf ook door. Alle toekomstige lessen werden daardoor full-time overgenomen door Jaromir.</p>
  <p>Na de middag pauze mochten we toen uiteindelijk zelf beginnen met programmeren. De kennis die we deze voormiddag opgedaan hadden werd ons stap voor stap uitgelegd terwijl we deze moesten toepassen in een test project. </p>
  <p>Dit testproject zou later gaan uitgroeien tot de applicatie die we deze week moesten ontwikkelen. </p>
  <img src="../../../assets/images/busit/busit2.jpg" alt="Group going to campus"  class="img-fluid" />
  <br>
  <br>
  <p>Om 17.00 uur werd de eerste lesdag stopgezet. Pavel had een evenement gepland in de stad zelf, dit bleek een heuse party-tram te zijn achteraf. Waarin gratis drank en eten beschikbaar was terwijl we verschillende stukken van de stad te zien kregen.</p>
  <img src="../../../assets/images/busit/busit3.jpg" alt="Group going to campus"  class="img-fluid" />
  <br>
  <br>
  <br>

  <h5>Dinsdag, 04/04/2017</h5>
  <p>De tweede dag begon met een seminarie over het gebruik van de Maps API van Google en het gebruik van de Estimote Beacons. Dit nam heel veel tijd in beslag en heeft ervoor gezorgd dat we niet veel meer theorie gezien hebben die dag.</p>
  <p>Natuurlijk, het onderwerp van deze week was “Location-Based apps” dus het was te verwachten dat dit enige tijd in beslag ging nemen. Het was bovendien een uitgebreid onderwerp waar heel veel over te vertellen was en heel veel in mogelijk was.</p>
  <img src="../../../assets/images/busit/busit4.jpg" alt="Group going to campus"  class="img-fluid" />
  <br>
  <br>
  <br>

  <h5>Woensdag, 05/04/2017</h5>
  <p>Woensdagvoormiddag werden alle seminaries afgewerkt die we nodig hadden om zelf te kunnen beginnen ontwikkelen. Hier werd vooral aandacht besteed aan de verschillende “activity triggers” die we moesten gebruiken de komende dagen.</p>
  <p>In de namiddag was het tijd om te brainstormen en ons idee uit te leggen bij Jaromir en Jan. Zij zouden dan kijken of het de moeite was en of het haalbaar was om dit te maken op de resterende tijd.</p>
  <p>Het team waar ik in zat had besloten om een mobiele variant van Cluedo te ontwikkelen. De map die je meekrijgt zou je leiden naar verschillende vraagstukken en ieder vraagstuk dat je juist beantwoorden zou een hint opleveren over wie de dader was.</p>
  <p>Nadat je op het einde van het spel kwam kreeg je een lijst te zien met alle mogelijke daders en moest je de correcte uit het lijstje kiezen. Iedere vraag die juist beantwoord werd (inclusief het kiezen van de dader) leverde punten op.</p>
  <p>Nadat ons idee was goedgekeurd werd er hier de rest van de dag aan verder gewerkt. In tegenstelling tot andere groepen hadden wij besloten geen mock-ups te maken, ons design zouden we simpel houden en wij zouden vooral focussen op een applicatie die werkte en alle nodige functionaliteit bevatten.  Wij begonnen daarom al onmiddellijk met programmeren in tegenstelling tot alle andere groepen.</p>
  <img src="../../../assets/images/busit/busit5.jpg" alt="Group going to campus"  class="img-fluid" />
  <br>
  <br>
  <br>

  <h5>Donderdag, 06/04/2017</h5>
  <p>De voorlaatste dag was volledig gewijd aan het werken aan de app. Van ’s morgens 08.30 tot 18.00 ben ik bezig geweest, met enkel in korte pauze tijdens de middag.</p>
  <p>Hier liep het jammer genoeg een beetje mis, aangezien niet iedereen van mijn team even gemotiveerd was om samen te werken. Enkele teamleden kwamen zelfs meerdere uren te laat opdagen, of vertrokken vele uren te vroeg en deden niets tot weinig gedurende de dag.</p>
  <p>Dit was jammer, aangezien het werk hierdoor grotendeels op mijn en twee andere teamleden gevallen was. Dit zou ons echter niet tegenhouden, wij zouden er het beste van maken. Iets wat niet altijd even makkelijk was want dit was toch wel een uitdagend project.</p>
  <p>We hadden redelijk wat boilerplate code die we moesten aanpassen, maar dit leiden vaak tot problemen en crashes. Gelukkig waren Jan en Jaromir meer dan bereid om te komen helpen in deze situaties.</p>
  <img src="../../../assets/images/busit/busit6.jpg" alt="Group going to campus"  class="img-fluid" />
  <br>
  <br>
  <p>Nadat de werkdag was afgelopen was er nog een wijndegustatie georganiseerd die diende als afscheidsfeestje. Ik ben altijd wel te vinden voor een glaasje alcohol, zeker voor meerdere, dus ik heb veel plezier beleefd aan deze avond.</p>
  <p>Gedurende deze avonden werden er meerdere roden en witte wijnen voorgeschoteld, deze varieerde radicaal van kwaliteit. Er waren er bij die ik enorm goed vond, maar het tegenovergestelde was ook waar. Bij sommige glazen heb ik echt moeite moeten doen om het leeg te kunnen drinken. </p>
  <p>De wijn was vergezeld van zelfgemaakt brood en kaas. Ja hoor, meer dan een geslaagde avond. </p>
  <img src="../../../assets/images/busit/busit7.jpg" alt="Group going to campus"  class="img-fluid" />
  <br>
  <br>
  <br>

  <h5>Vrijdag, 07/04/2017</h5>
  <p>De laatste dag hadden we nog een uurtje de tijd gekregen om onze app af te maken. Gedurende deze periode was het enige wat in mijn groep nog moest gebeuren het kiezen van de locatie van de vraagstukken. </p>
  <p>Normaal zou na dit uurtje, iedere groep iedere app moeten gaan testen en beoordelen. Maar zo ver is het jammer genoeg nooit gekomen vanwege het slechte weer. Wat ik zeer jammer vond, enkel de groep waarin ik zat heeft uiteindelijk een volledig werkende app afgeleverd en het eindresultaat mocht zeker gezien worden.</p>
  <p>De noodoplossing was een PowerPointpresentatie  maken van je app, en deze dan te pitchen naar de andere groepen. Op basis van deze presentatie werd vervolgens een score toegekend. Persoonlijk vond ik dit heel oneerlijk (aangezien de winnende groep niet meer dan wireframes had en nog geen lijn cde had geschreven).</p>
  <p>De winnaar kreeg een set mee van drie Estimote Beacons. Omdat er nog één pak over was hebben Jaromir en Jan deze nog uitgedeeld aan de mensen waarin zij potentieel zagen en die goed meegewerkt hadden deze week. Twee van deze drie overblijvende beacons zijn uiteindelijk in handen gevallen van een PXL student, waaronder eentje in die van mij.</p>
  <p>Hierna was er nog een korte speech van Pavel, Jaromir en Jan en zat het officiële programma van de Bus-IT week er volledig op.</p>
  <img src="../../../assets/images/busit/busit8.jpg" alt="Group going to campus"  class="img-fluid" />
  <br>
  <br>
  <br>

  <h5>Reflectie</h5>
  <p>De BusIT week was een uiterst leerrijke week voor mij. Terwijl ik wel al kennis had van Java, de taal die gebruikt wordt bij Android development voelde alles hier toch volledig nieuw aan. De manier waarop je moet programmeren in Android is totaal anders dan de manier waarop ik tot nu toe gewoon Java gedaan heb.</p>
  <p>Android zit fundamenteel anders in elkaar dan Java, zo denk ik al snel aan activities en lifecycle events die de hele flow van je applicatie bepalen. De GUI die op een totaal andere manier ontwikkeld wordt en alles wat met resources te maken heeft. Hoe je een lijst kan maken waar je door scrolt was ook iets wat veel uitgebreider was dan dat ik verwacht had. Allemaal belangrijke elementen van Android, en mobile development in het algemeen, die niet te vinden zijn in Java zelf.</p>
  <p>Dit is dan ook nog niet eens het enige nieuwe wat ik hier geleerd heb. We hebben hier niet enkel de basis gezien van Android development maar ook nog enkele geavanceerde technieken. Het gebruik van Google Maps of de Estimote Beacons zijn hier voorbeelden van.</p>
  <p>Ik ben blij dat ik een goede beheersing had van Java toen ik deze week aanvatten. Ik vrees dat het heel wat minder vlot verlopen zou zijn, moest dit niet het geval geweest zijn. Er was al maar heel weinig tijd om dit project af te kunnen ronden, mocht ik in een taal hebben moeten werken die ik minder goed beheerste denk ik niet dat ik alles werkende gekregen zou hebben. </p>
  <p>Ik ben zeer blij hier aan meegedaan te hebben, want alles wat ik hier geleerd heb wordt natuurlijk ook meegenomen in mijn verdere carrière, zowel op school als in mijn latere loopbaan. Deze week heeft mij ook een enorme boost gegeven voor het vak Mobile Development wat ik in het laatste jaar van mijn opleiding gevolgd heb, aangezien vrijwel alles wat er tijdens deze lessen behandeld geworden geweest is, als kort aan bod gekomen is tijdens de BusIT week.</p>
  <p>Ik zou deze ervaring zo opnieuw doen mocht ik de kans krijgen, want het is uiteindelijk niet allemaal “work” er is ook genoeg tijd beschikbaar voor “pleasure”. Tijdens deze week heb ik ook kunnen genieten van een ander land en heb ik ook daar veel gezien en bij geleerd. Ik heb niet alleen nieuwe technologieën leren kennen, maar je leert ook andere mensen kennen van over de hele wereld en ermee samenwerken. Ik heb de BusIT opgenomen in mijn portfolio omdat ik dit een ongelofelijk ervaring vond, een ervaring die gedeeld moest worden en één van de hoogtepunten van mijn opleiding.</p>     
  <img src="../../../assets/images/busit/busit9.jpg" alt="Group going to campus"  class="img-fluid" />
</div>
