// italentangular/src/app/components/sems/infofarm/infofarm.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-infofarm',
  templateUrl: './infofarm.component.html',
  styleUrls: ['./infofarm.component.css']
})
export class InfofarmComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
  <h3>InfoFarm - “Deep Learning”</h3>
  <h4>10/01/2018 @ Corda Conference</h4>
  <br>

  <p>Het onderwerp Artificiële intelligentie is er eentje waar ik meerdere seminaries over gevolgd heb, het laatste seminarie over dit onderwerp werd gegeven door InfoFarm. InfoFarm is een data science en big data bedrijf dat deel uitmaakt van de Xplore Group (Chronos).</p>
  <p>Dit seminarie behandelde voornamelijk het onderwerp “deep learning”. Er werd gefocust op waarom deep learning plots zo populair geworden is, de geschiedenis van deep learning, en welke technologieën hierbij gebruikt worden (voornamelijk TensorFlow). Het seminarie eindigde met een zeer uitgebreide demonstratie van wat InfoFarm “de hello-world van de AI” noemde.</p>
  <p>Dit was één van de laatste seminaries die ik gevolgd heb maar wel één die mij het beste is bijgebleven. Het concrete voorbeeld heeft echt duidelijk gemaakt wat er precies allemaal mogelijk is en hoe het precies in zijn werk gaat. De theorie werd hier heel visueel en stap voor stap getoond en heeft mij over de lijn getrokken om uiteindelijk Python te leren. De overlap met de andere seminaries rond dit onderwerp hebben mij ook geholpen deze uiteindelijk beter te begrijpen.</p>
  
</div>

// italentwebsite/src/components/seminaries/infofarm.jsx
import React  from 'react';

const InfoFarm = () => {
    return (
        <div className="container">
            <h3>InfoFarm - “Deep Learning”</h3>
            <h4>10/01/2018 @ Corda Conference</h4>
            <br></br>

            <p>Het onderwerp Artificiële intelligentie is er eentje waar ik meerdere seminaries over gevolgd heb, het laatste seminarie over dit onderwerp werd gegeven door InfoFarm. InfoFarm is een data science en big data bedrijf dat deel uitmaakt van de Xplore Group (Chronos).</p>
            <p>Dit seminarie behandelde voornamelijk het onderwerp “deep learning”. Er werd gefocust op waarom deep learning plots zo populair geworden is, de geschiedenis van deep learning, en welke technologieën hierbij gebruikt worden (voornamelijk TensorFlow). Het seminarie eindigde met een zeer uitgebreide demonstratie van wat InfoFarm “de hello-world van de AI” noemde.</p>
            <p>Dit was één van de laatste seminaries die ik gevolgd heb maar wel één die mij het beste is bijgebleven. Het concrete voorbeeld heeft echt duidelijk gemaakt wat er precies allemaal mogelijk is en hoe het precies in zijn werk gaat. De theorie werd hier heel visueel en stap voor stap getoond en heeft mij over de lijn getrokken om uiteindelijk Python te leren. De overlap met de andere seminaries rond dit onderwerp hebben mij ook geholpen deze uiteindelijk beter te begrijpen.</p>
            
        </div>
    );
};

export default InfoFarm;
