// italentangular/src/app/components/sems/smartict/smartict.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-smartict',
  templateUrl: './smartict.component.html',
  styleUrls: ['./smartict.component.css']
})
export class SmartictComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
  <h3>Smart ICT – “Artificiële Intelligentie”</h3>
  <h4>18/12/2017 @ PXL B223</h4>
  <br>

  <p>Smart ICT van PXL had ook een seminarie georganiseerd rond het onderwerp AI. Dit seminarie begon met een korte introductie tot het Robotics Lab van de PXL vooraleer het seminarie zelf begon.</p>
  <p>Ik ben blij dat ieder seminarie over AI een andere insteek had op het onderwerp. Dit seminarie focuste vrijwel uitsluitend op de werking van convolutional neural networks en recurrent neural networks.</p>
  <p>Het was een zeer theoretisch seminarie en één van de moeilijkere om mentaal te kunnen verwerken. Dit betekend echter niet dat het niet interessant was, ik was aan het scherm gekluisterd tot aan het einde, ook al was ik niet onmiddellijk mee met alles wat er verteld is geworden. Gelukkig is veel van dit seminarie mij duidelijk geworden na het seminarie van InfoFarm.</p>
  
</div>

// italentwebsite/src/components/seminaries/smartict.jsx
import React  from 'react';

const SmartIct = () => {
    return (
        <div className="container">
            <h3>Smart ICT – “Artificiële Intelligentie”</h3>
            <h4>18/12/2017 @ PXL B223</h4>
            <br></br>

            <p>Smart ICT van PXL had ook een seminarie georganiseerd rond het onderwerp AI. Dit seminarie begon met een korte introductie tot het Robotics Lab van de PXL vooraleer het seminarie zelf begon.</p>
            <p>Ik ben blij dat ieder seminarie over AI een andere insteek had op het onderwerp. Dit seminarie focuste vrijwel uitsluitend op de werking van convolutional neural networks en recurrent neural networks.</p>
            <p>Het was een zeer theoretisch seminarie en één van de moeilijkere om mentaal te kunnen verwerken. Dit betekend echter niet dat het niet interessant was, ik was aan het scherm gekluisterd tot aan het einde, ook al was ik niet onmiddellijk mee met alles wat er verteld is geworden. Gelukkig is veel van dit seminarie mij duidelijk geworden na het seminarie van InfoFarm.</p>
            
        </div>
    );
};

export default SmartIct;
