// italentwebsite/src/components/seminaries/euricom.jsx
import React  from 'react';

const Euricom = () => {
    return (
        <div className="container">
            <h3>Euricom - “VueJS”</h3>
            <h4>28/03/2017 @ B151</h4>
            <br></br>

            <p>De Javascript wereld is er ééntje die razendsnel vooruit gaat en constant veranderd. Vele frameworks komen en gaan, maar Angular en React blijven bestaan. Of is er een derde speler op de markt? Dat is de vraag die Euricom stelde tijdens dit seminarie over VueJS.</p>
            <p>VueJS is een up en coming javascript framework dat de beste eigenschappen van Angular en React combineert in een volledig nieuw framework. Ik had tot dit seminarie nog niet gehoord van VueJS, alles wat verteld werd was nieuw voor mij. Maar ik vond het wel enorm interessant en heb achteraf zelf wat geëxperimenteerd met VueJS.</p>
            <p>Dit seminarie was er één dat ik iedereen kan aanraden aangezien het aantrekkelijk gebracht was en de perfecte balans had tussen theorie en praktijk. VueJS is bovendien een heel fijn framework om mee te werken en zeker één dat ik later nog hoop te gebruiken. Ik kan ook eerlijk zeggen dat ik zonder dit seminarie het waarschijnlijk nooit gebruikt zou hebben.</p>
            
        </div>
    );
};

export default Euricom;

// italentangular/src/app/components/sems/euricom/euricom.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-euricom',
  templateUrl: './euricom.component.html',
  styleUrls: ['./euricom.component.css']
})
export class EuricomComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
  <h3>Euricom - “VueJS”</h3>
  <h4>28/03/2017 @ B151</h4>
  <br>

  <p>De Javascript wereld is er ééntje die razendsnel vooruit gaat en constant veranderd. Vele frameworks komen en gaan, maar Angular en React blijven bestaan. Of is er een derde speler op de markt? Dat is de vraag die Euricom stelde tijdens dit seminarie over VueJS.</p>
  <p>VueJS is een up en coming javascript framework dat de beste eigenschappen van Angular en React combineert in een volledig nieuw framework. Ik had tot dit seminarie nog niet gehoord van VueJS, alles wat verteld werd was nieuw voor mij. Maar ik vond het wel enorm interessant en heb achteraf zelf wat geëxperimenteerd met VueJS.</p>
  <p>Dit seminarie was er één dat ik iedereen kan aanraden aangezien het aantrekkelijk gebracht was en de perfecte balans had tussen theorie en praktijk. VueJS is bovendien een heel fijn framework om mee te werken en zeker één dat ik later nog hoop te gebruiken. Ik kan ook eerlijk zeggen dat ik zonder dit seminarie het waarschijnlijk nooit gebruikt zou hebben.</p>
  
</div>
