// italentwebsite/src/components/seminaries/mediafoundry.jsx
import React  from 'react';

const MediaFoundry = () => {
    return (
        <div className="container">
            <h3>IDA-MediaFoundry - “Internet of Things”</h3>
            <h4>16/05/2017 @ Corda Conference</h4>
            <br></br>

            <p>IDA-MediaFoundry, lid van de Xplore Group (Chronos) heeft een seminarie georganiseerd over “Internet of Things” (IoT). Dit seminarie gaf een introductie tot wat IoT precies is en hoe het precies werkte.</p>
            <p>Dit seminarie had ook een enorm grootte hands-on sessie waarbij IDA-MediaFoundry enkele IoT devices ter beschikking stelde om mee te experimenteren. Het was vooral dit deel waar ik veel uit geleerd heb, aangezien dit mijn eerste hand-on ervaring was met een IoT device.</p>
            
        </div>
    );
};

export default MediaFoundry;

// italentangular/src/app/components/sems/mediafoundry/mediafoundry.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-mediafoundry',
  templateUrl: './mediafoundry.component.html',
  styleUrls: ['./mediafoundry.component.css']
})
export class MediafoundryComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
  <h3>IDA-MediaFoundry - “Internet of Things”</h3>
  <h4>16/05/2017 @ Corda Conference</h4>
  <br>

  <p>IDA-MediaFoundry, lid van de Xplore Group (Chronos) heeft een seminarie georganiseerd over “Internet of Things” (IoT). Dit seminarie gaf een introductie tot wat IoT precies is en hoe het precies werkte.</p>
  <p>Dit seminarie had ook een enorm grootte hands-on sessie waarbij IDA-MediaFoundry enkele IoT devices ter beschikking stelde om mee te experimenteren. Het was vooral dit deel waar ik veel uit geleerd heb, aangezien dit mijn eerste hand-on ervaring was met een IoT device.</p>
  
</div>
