// italentangular/src/app/components/python/python.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-python',
  templateUrl: './python.component.html',
  styleUrls: ['./python.component.css']
})
export class PythonComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
  <h3>Python - “Fundamentals”</h3>
  <h4>2017 @ Pluralsight</h4>
  <br>

  <p>Sinds het seminarie van Craftworkz omtrent AI en de opmerking dat, als je echt iets met AI wilt wilt doen, je Python moet kennen, heb ik er over nagedacht deze taal aan te leren. Ik heb uiteindelijk besloten het te doen toen ik van vele medestudenten, en mensen in het werkveld te horen kreeg hoe leuk en makkelijk Python wel niet was.</p>
  <p>Om Python te leren heb ik een Pluralsight cursus gevolgd die ontwikkeld is geworden door Robert Smallshire en Austin Bingham. Zij hebben een driedelige cursus ontwikkeld, met bijbehorend boek, dat steeds dieper en dieper de Python taal verkend. De cursus voor basis Python is getiteld “Python Fundamentals” en focust zich op de basis van de taal en op programma’s die hoofdzakelijk werken in de REPL (Read-Eval-Print-Loop).</p>
  <img src="../../../assets/images/python/python1.jpg" alt="Group going to campus"  class="img-fluid" />
  <br>
  <br>

  <h5>Verslag</h5>
  <p>De cursus begint met een korte geschiedenis van de taal, het verschil tussen Python 2  en Python 3 en een uitleg over wat de REPL precies is en hoe deze werkt.</p>
  <p>Python is een taal die uiterlijk toch wel wat differentieert van de meeste andere programmeertalen. De typerende {{"{}"}} zijn afwezig in Python en in plaats daarvan wordt er gebruik gemaakt van indentatie. Hierdoor is het heel belangrijk dat je duidelijk code schrijft in Python, aangezien je niet alles wat samen hoort kan dumpen tussen {{"{}"}}.</p>
  <p>Nadat dit achter de rug was begon echter de echte cursus. Deze behandelde in grote lijnen wat je verwacht van een cursus die de basis van een programmeertaal bespreekt. Zo kwamen de verschillende data types zoals integers of floats al snel aan bod, of het importeren van modules en methodes.</p>
  <p>Vervolgens kwamen de gebruikelijke loops (“if”, “while” en “for”) aan bod. Tot nu toe verliep nog alles zoals verwacht en was er nog niet zo heel erg veel verschillend van de programmeertalen die ik op dit punt al kende. </p>
  <p>Het was pas bij het volgende onderdeel, collections, dat de cursus een iets onverwachte wending nam en waar de kracht van Python stilaan begon boven te komen. De datatypes str, bytes, list, range, en dictionary waren vrij standaard maar de daaropvolgende set en tuple waren vooral interessant en heel wat meer unieker. Bij de tuple kwam al snel tuple-unpacking boven, iets waar ik toch wel even heb bij moeten stilstaan om te snappen wat het was, en hoe het te gebruiken.</p>
  <p>Van collecties ging de cursus vervolgens naar objecten. In dit hoofdstuk werd er in het bijzonder aandacht besteed aan concepten als pass-by-value en wat de implicaties hiervan zijn, hoe Python zijn typing systeem werkt en hoe scoping werkt. Ieder van deze onderwerpen waren anders dan dat ik gewoon was, maar niet noodzakelijk slechter.</p>
  <p>De volgende stap was het ontwikkelen van een module. Het was in dit hoofdstuk dat de focus ook over ging naar methodes, return values en de documentatie van code. Allemaal onderwerpen die ik wel gezien heb in andere talen, maar die Python toch net ietsje anders werken.</p>
  <p>Het opvangen en verwerken van exceptions was het volgende hoofdstuk. Dit hoofdstuk voelde heel bekend en duurde niet zo heel lang. Maar het was wel nodig, omdat alles samengebracht ging worden in het volgende hoofdstuk: klassen.</p>
  <p>Een klasse  in Python werkt toch nog net iets anders dan een klasse in een andere programmeertaal en is ideologisch verschillend dan klassen van een andere Object-Oriented Programming language (OOP). Tijdens dit hoofdstuk heb ik ook een oefening uitgewerkt die alle kennis tot op dit punt samenbracht en vooral focuste op mogelijkheden die mij op dit punt iets unieks aan Python leken.</p>
  <img src="../../../assets/images/python/python2.jpg" alt="Group going to campus"  class="img-fluid" />
  <br>
  <br>
  <p>De laatste paar hoofdstukken waren allemaal kleiner dan de voorgaande en focuste meer op geavanceerdere eigenschappen zoals Iterables, List Comprehensions, Generators en Input/Output. Allemaal onderwerpen die niet zo heel erg veel verschilde van de talen die ik op dit punt al kende.</p>
  <br>

  <h5>Reflectie</h5>
  <p>Aangezien ik geen voorkennis had van Python was het meeste wat ik gezien heb tijdens deze cursus in theorie nieuw voor mij. Het aanleren van Python was gelukkig niet zo heel erg moeilijk omdat ik tijdens mijn opleiding al verschillende programmeertalen gezien en aangeleerd heb gekregen, en veel van de concepten in die talen zijn ook terug te vinden in Python.</p>
  <p>Wat deze cursus mij vooral bijgebracht heeft, is het worden van een betere ontwikkelaar. Zoals eerder aangehaald bevat Python veel bekende concepten, maar veel van deze concepten zijn toch net iets anders of iets belangrijker om te begrijpen. Zo denk ik al snel aan pass-by-value of pass-by-reference, twee concepten die in andere talen ook voorkomen, maar me pas echt duidelijk zijn geworden door deze cursus omdat ze hier echt belangrijk zijn om te begrijpen, aangezien ze tot desastreuze gevolgen leiden als je hier een fout op maakt.</p>
  <p>Iterables is een volgende voorbeeld. Ik wist tot op dit punt wel wat een iterable is en hoe dit te gebruiken, maar wat er achterliggend gebeurd was mij altijd een mysterie. Dankzij deze cursus en de heldere uitleg omtrent dit onderwerp is het mij nu echter wel duidelijk.</p>
  <p>Python is ook een taal die iets meer low-level is dan C# of Java, je moest er iets meer zelf in doen. Dit heeft ervoor gezorgd dat ik iets meer inzicht moest hebben in wat ik bezig was, zeker wanneer het neerkomt op geavanceerde mogelijkheden zoals tuple-unpacking of list comprehensions.</p>
  <p>De kennis die ik hier heb opgedaan neem ik daarom ook mee naar andere programmeertalen, het aanleren van een nieuw taal heeft mij dus beter gemaakt in het beoefenen van talen die ik al reeds kende.</p>
  <p>Python was een zeer fijne taal om te leren. Omdat dit een basis cursus is, was het niet echt moeilijk en daarom verliep de cursus ook zeer vlot zonder enige echte problemen. Ergens vind ik het zelfs jammer dat deze taal niet aangeboden wordt tijdens de opleiding zelf, zeker omdat Python in de toekomst zeker en vast belangrijker en belangrijker zal worden (AI). </p>
  <p>Ik sta momenteel op het punt om de twee vervolgcursussen nog te volgen, maar deze gaan niet behandeld zijn voor de deadline van het I-Talent portfolio en worden er daarom niet in opgenomen. </p>
</div>

// italentwebsite/src/components/innovatie/python.jsx
import React  from 'react';

const Python = () => {
    return (
        <div className="container">
            <h3>Python - “Fundamentals”</h3>
            <h4>2017 @ Pluralsight</h4>
            <br></br>

            <p>Sinds het seminarie van Craftworkz omtrent AI en de opmerking dat, als je echt iets met AI wilt wilt doen, je Python moet kennen, heb ik er over nagedacht deze taal aan te leren. Ik heb uiteindelijk besloten het te doen toen ik van vele medestudenten, en mensen in het werkveld te horen kreeg hoe leuk en makkelijk Python wel niet was.</p>
            <p>Om Python te leren heb ik een Pluralsight cursus gevolgd die ontwikkeld is geworden door Robert Smallshire en Austin Bingham. Zij hebben een driedelige cursus ontwikkeld, met bijbehorend boek, dat steeds dieper en dieper de Python taal verkend. De cursus voor basis Python is getiteld “Python Fundamentals” en focust zich op de basis van de taal en op programma’s die hoofdzakelijk werken in de REPL (Read-Eval-Print-Loop).</p>
            <br></br>

            <h5>Verslag</h5>
            <p>De cursus begint met een korte geschiedenis van de taal, het verschil tussen Python 2  en Python 3 en een uitleg over wat de REPL precies is en hoe deze werkt.</p>
            <p>Python is een taal die uiterlijk toch wel wat differentieert van de meeste andere programmeertalen. De typerende “{"{ }"}-haakjes” zijn afwezig in Python en in plaats daarvan wordt er gebruik gemaakt van indentatie. Hierdoor is het heel belangrijk dat je duidelijk code schrijft in Python, aangezien je niet alles wat samen hoort kan dumpen tussen {"{ }"}.</p>
            <p>Nadat dit achter de rug was begon echter de echte cursus. Deze behandelde in grote lijnen wat je verwacht van een cursus die de basis van een programmeertaal bespreekt. Zo kwamen de verschillende data types zoals integers of floats al snel aan bod, of het importeren van modules en methodes.</p>
            <p>Vervolgens kwamen de gebruikelijke loops (“if”, “while” en “for”) aan bod. Tot nu toe verliep nog alles zoals verwacht en was er nog niet zo heel erg veel verschillend van de programmeertalen die ik op dit punt al kende. </p>
            <p>Het was pas bij het volgende onderdeel, collections, dat de cursus een iets onverwachte wending nam en waar de kracht van Python stilaan begon boven te komen. De datatypes str, bytes, list, range, en dictionary waren vrij standaard maar de daaropvolgende set en tuple waren vooral interessant en heel wat meer unieker. Bij de tuple kwam al snel tuple-unpacking boven, iets waar ik toch wel even heb bij moeten stilstaan om te snappen wat het was, en hoe het te gebruiken.</p>
            <p>Van collecties ging de cursus vervolgens naar objecten. In dit hoofdstuk werd er in het bijzonder aandacht besteed aan concepten als pass-by-value en wat de implicaties hiervan zijn, hoe Python zijn typing systeem werkt en hoe scoping werkt. Ieder van deze onderwerpen waren anders dan dat ik gewoon was, maar niet noodzakelijk slechter.</p>
            <p>De volgende stap was het ontwikkelen van een module. Het was in dit hoofdstuk dat de focus ook over ging naar methodes, return values en de documentatie van code. Allemaal onderwerpen die ik wel gezien heb in andere talen, maar die Python toch net ietsje anders werken.</p>
            <p>Het opvangen en verwerken van exceptions was het volgende hoofdstuk. Dit hoofdstuk voelde heel bekend en duurde niet zo heel lang. Maar het was wel nodig, omdat alles samengebracht ging worden in het volgende hoofdstuk: klassen.</p>
            <p>Een klasse  in Python werkt toch nog net iets anders dan een klasse in een andere programmeertaal en is ideologisch verschillend dan klassen van een andere Object-Oriented Programming language (OOP). Tijdens dit hoofdstuk heb ik ook een oefening uitgewerkt die alle kennis tot op dit punt samenbracht en vooral focuste op mogelijkheden die mij op dit punt iets unieks aan Python leken.</p>
            <p>De laatste paar hoofdstukken waren allemaal kleiner dan de voorgaande en focuste meer op geavanceerdere eigenschappen zoals Iterables, List Comprehensions, Generators en Input/Output. Allemaal onderwerpen die niet zo heel erg veel verschilde van de talen die ik op dit punt al kende.</p>
            <br></br>

            <h5>Reflectie</h5>
            <p>Aangezien ik geen voorkennis had van Python was het meeste wat ik gezien heb tijdens deze cursus in theorie nieuw voor mij. Het aanleren van Python was gelukkig niet zo heel erg moeilijk omdat ik tijdens mijn opleiding al verschillende programmeertalen gezien en aangeleerd heb gekregen, en veel van de concepten in die talen zijn ook terug te vinden in Python.</p>
            <p>Wat deze cursus mij vooral bijgebracht heeft, is het worden van een betere ontwikkelaar. Zoals eerder aangehaald bevat Python veel bekende concepten, maar veel van deze concepten zijn toch net iets anders of iets belangrijker om te begrijpen. Zo denk ik al snel aan pass-by-value of pass-by-reference, twee concepten die in andere talen ook voorkomen, maar me pas echt duidelijk zijn geworden door deze cursus omdat ze hier echt belangrijk zijn om te begrijpen, aangezien ze tot desastreuze gevolgen leiden als je hier een fout op maakt.</p>
            <p>Iterables is een volgende voorbeeld. Ik wist tot op dit punt wel wat een iterable is en hoe dit te gebruiken, maar wat er achterliggend gebeurd was mij altijd een mysterie. Dankzij deze cursus en de heldere uitleg omtrent dit onderwerp is het mij nu echter wel duidelijk.</p>
            <p>Python is ook een taal die iets meer low-level is dan C# of Java, je moest er iets meer zelf in doen. Dit heeft ervoor gezorgd dat ik iets meer inzicht moest hebben in wat ik bezig was, zeker wanneer het neerkomt op geavanceerde mogelijkheden zoals tuple-unpacking of list comprehensions.</p>
            <p>De kennis die ik hier heb opgedaan neem ik daarom ook mee naar andere programmeertalen, het aanleren van een nieuw taal heeft mij dus beter gemaakt in het beoefenen van talen die ik al reeds kende.</p>
            <p>Python was een zeer fijne taal om te leren. Omdat dit een basis cursus is, was het niet echt moeilijk en daarom verliep de cursus ook zeer vlot zonder enige echte problemen. Ergens vind ik het zelfs jammer dat deze taal niet aangeboden wordt tijdens de opleiding zelf, zeker omdat Python in de toekomst zeker en vast belangrijker en belangrijker zal worden (AI). </p>
            <p>Ik sta momenteel op het punt om de twee vervolgcursussen nog te volgen, maar deze gaan niet behandeld zijn voor de deadline van het I-Talent portfolio en worden er daarom niet in opgenomen. </p>
            
        </div>
    );
};

export default Python;
