// italentwebsite/src/components/seminaries/craftworkz.jsx
import React  from 'react';

const Craftworkz = () => {
    return (
        <div className="container">
            <h3>Craftworkz - “AI en Robotics”</h3>
            <h4>02/05/2017 @ Corda Conference</h4>
            <br></br>

            <p>Als je me vandaag vraagt welk seminarie mij het meest is bijgebleven en waar ik het meeste uit heb geleerd zal ik je met veel enthousiasme vertellen over dit het seminarie van Craftworkz over artificiële intelligentie en robotics.</p>
            <p>Craftworkz is een bedrijf dat deel uitmaakt van de Xplore Group en het bedrijf wat gezorgd heeft voor mijn eerste contact met AI. Dit seminarie vertelde eerder high level over hoe AI precies in zijn werk ging, en trad niet teveel in details over de achterliggende algoritmes. Wat dit seminarie wel deed was een overvloed aan voorbeelden tonen over de mogelijk implementaties. Ieder voorbeeld was al interessanter dan het andere (dit liep van Chatbots tot AI die hielp in winkels). Het tweede deel van dit seminarie was een hands-on sessie met IBM Watson, waarin je zelf op een eenvoudige manier een Chabot kon ontwikkelen.</p>
            <p>Het was dit seminarie wat er voor gezorgd heeft dat ik een interesse in AI ontwikkeld heb. Tot dit seminarie dacht ik dat AI enkel weggelegd was voor de aller slimste ontwikkelaars, na dit seminarie heb ik geleerd dat het een thema is waar iedereen aan kan beginnen en veel uit kan leren.</p>
            
        </div>
    );
};

export default Craftworkz;

// italentangular/src/app/components/sems/craftworkz/craftworkz.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-craftworkz',
  templateUrl: './craftworkz.component.html',
  styleUrls: ['./craftworkz.component.css']
})
export class CraftworkzComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
  <h3>Craftworkz - “AI en Robotics”</h3>
  <h4>02/05/2017 @ Corda Conference</h4>
  <br>

  <p>Als je me vandaag vraagt welk seminarie mij het meest is bijgebleven en waar ik het meeste uit heb geleerd zal ik je met veel enthousiasme vertellen over dit het seminarie van Craftworkz over artificiële intelligentie en robotics.</p>
  <p>Craftworkz is een bedrijf dat deel uitmaakt van de Xplore Group en het bedrijf wat gezorgd heeft voor mijn eerste contact met AI. Dit seminarie vertelde eerder high level over hoe AI precies in zijn werk ging, en trad niet teveel in details over de achterliggende algoritmes. Wat dit seminarie wel deed was een overvloed aan voorbeelden tonen over de mogelijk implementaties. Ieder voorbeeld was al interessanter dan het andere (dit liep van Chatbots tot AI die hielp in winkels). Het tweede deel van dit seminarie was een hands-on sessie met IBM Watson, waarin je zelf op een eenvoudige manier een Chabot kon ontwikkelen.</p>
  <p>Het was dit seminarie wat er voor gezorgd heeft dat ik een interesse in AI ontwikkeld heb. Tot dit seminarie dacht ik dat AI enkel weggelegd was voor de aller slimste ontwikkelaars, na dit seminarie heb ik geleerd dat het een thema is waar iedereen aan kan beginnen en veel uit kan leren.</p>
  
</div>
