// italentwebsite/src/components/seminaries/cegeka.jsx
import React  from 'react';

const Cegeka = () => {
    return (
        <div className="container">
            <h3>Cegeka - XP practices, SOLID, TDD en Craftsmanship</h3>
            <h4>21/03/2017 @ PXL B341</h4>
            <br></br>

            <p>Eén van de eerste seminaries die ik gevolgd heb was georganiseerd door Cegeka. Dit was een all-round programming seminarie waarop er gefocust werd op meerdere onderdelen, maar vooral testing stond centraal.</p>
            <p>Het grootste deel van dit seminarie bestond uit het nabootsen van een project waarin de requirements op snel tempo veranderde. Deze oefening moest Test-Driven (Development) (TDD) uitgevoerd worden en gebeurde via de principes van Extreme Programming (XP), een manier waarop je via peer programming samen werkt aan een project. Tijdens deze oefening moesten we een variatie ontwikkelen op “the game of life”.</p>
            <p>Gedurende dit seminarie werden er veel best practises en tips geven om dit tot een zo goed mogelijk eind te kunnen brengen. Ik heb hier veel uit geleerd, omdat het de eerste keer was dat ik een probleem op deze manier heb aangepakt. Het voelt heel anders om met twee over een project na te denken. Maar het was vooral het TDD gedeelde waar ik het meeste aan heb moeten wennen om onder de knie te kunnen krijgen. TDD is iets wat in de bedrijfswereld veel gebruikt wordt en dit seminarie heeft me geleerd dat het iets is waar ik meer aandacht aan moet besteden, het is niet iets wat je zomaar zonder erop te oefenen kunt aanleren.</p>
            
        </div>
    );
};

export default Cegeka;

// italentangular/src/app/components/sems/cegeka/cegeka.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-cegeka',
  templateUrl: './cegeka.component.html',
  styleUrls: ['./cegeka.component.css']
})
export class CegekaComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
  <h3>Cegeka - XP practices, SOLID, TDD en Craftsmanship</h3>
  <h4>21/03/2017 @ PXL B341</h4>
  <br>

  <p>Eén van de eerste seminaries die ik gevolgd heb was georganiseerd door Cegeka. Dit was een all-round programming seminarie waarop er gefocust werd op meerdere onderdelen, maar vooral testing stond centraal.</p>
  <p>Het grootste deel van dit seminarie bestond uit het nabootsen van een project waarin de requirements op snel tempo veranderde. Deze oefening moest Test-Driven (Development) (TDD) uitgevoerd worden en gebeurde via de principes van Extreme Programming (XP), een manier waarop je via peer programming samen werkt aan een project. Tijdens deze oefening moesten we een variatie ontwikkelen op “the game of life”.</p>
  <p>Gedurende dit seminarie werden er veel best practises en tips geven om dit tot een zo goed mogelijk eind te kunnen brengen. Ik heb hier veel uit geleerd, omdat het de eerste keer was dat ik een probleem op deze manier heb aangepakt. Het voelt heel anders om met twee over een project na te denken. Maar het was vooral het TDD gedeelde waar ik het meeste aan heb moeten wennen om onder de knie te kunnen krijgen. TDD is iets wat in de bedrijfswereld veel gebruikt wordt en dit seminarie heeft me geleerd dat het iets is waar ik meer aandacht aan moet besteden, het is niet iets wat je zomaar zonder erop te oefenen kunt aanleren.</p>
  
</div>
